-- MySQL Script generated by MySQL Workbench
-- 01/05/16 18:09:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema impulse
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema impulse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `impulse` DEFAULT CHARACTER SET utf8 ;
USE `impulse` ;

-- -----------------------------------------------------
-- Table `impulse`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `impulse`.`roles` ;

CREATE TABLE IF NOT EXISTS `impulse`.`roles` (
  `ID` INT NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  PRIMARY KEY (`role`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `impulse`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `impulse`.`users` ;

CREATE TABLE IF NOT EXISTS `impulse`.`users` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `enabled` TINYINT NULL DEFAULT 1,
  `roles_role` VARCHAR(45) NOT NULL,
  `ID` INT AUTO_INCREMENT,
  `account` DECIMAL(10,2) NULL DEFAULT '0.0',
  `create_time`DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  INDEX `fk_user_roles_idx` (`roles_role` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  CONSTRAINT `fk_user_roles`
    FOREIGN KEY (`roles_role`)
    REFERENCES `impulse`.`roles` (`role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `impulse`.`phone_numbers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `impulse`.`phone_numbers` ;

CREATE TABLE IF NOT EXISTS `impulse`.`phone_numbers` (
  `number` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `user_email` VARCHAR(255) NULL,
  PRIMARY KEY (`number`),
  INDEX `fk_phone_numbers_user1_idx` (`user_email` ASC),
  CONSTRAINT `fk_phone_numbers_user1`
    FOREIGN KEY (`user_email`)
    REFERENCES `impulse`.`users` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `impulse`.`plans`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `impulse`.`plans` ;

CREATE TABLE IF NOT EXISTS `impulse`.`plans` (
  `ID` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `price` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `plans_ID_UNIQUE` (`ID` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `impulse`.`deals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `impulse`.`deals` ;

CREATE TABLE IF NOT EXISTS `impulse`.`deals` (
  `ID` INT NOT NULL,
  `users_email` VARCHAR(255) NOT NULL,
  `plans_ID` INT NOT NULL,
  `made_time` DATETIME NOT NULL,
  `expire_time` DATETIME NULL,
  INDEX `fk_deals_users1_idx` (`users_email` ASC),
  INDEX `fk_deals_plans1_idx` (`plans_ID` ASC),
  UNIQUE INDEX `deal_id_UNIQUE` (`ID` ASC),
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_deals_users1`
    FOREIGN KEY (`users_email`)
    REFERENCES `impulse`.`users` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_deals_plans1`
    FOREIGN KEY (`plans_ID`)
    REFERENCES `impulse`.`plans` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `impulse`.`connections`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `impulse`.`connections` ;

CREATE TABLE IF NOT EXISTS `impulse`.`connections` (
  `phone_number` INT NOT NULL,
  `calling_to` INT NOT NULL,
  `duration` INT NOT NULL COMMENT 'In seconds',
  `end_time` DATETIME NOT NULL,
  INDEX `fk_connections_phone_numbers1_idx` (`phone_number` ASC),
  CONSTRAINT `fk_connections_phone_numbers1`
    FOREIGN KEY (`phone_number`)
    REFERENCES `impulse`.`phone_numbers` (`number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `impulse`.`texts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `impulse`.`texts` ;

CREATE TABLE IF NOT EXISTS `impulse`.`texts` (
  `phone_number` INT NOT NULL,
  `sent_to` INT NOT NULL,
  `sent_time` DATETIME NOT NULL,
  INDEX `fk_texts_phone_numbers1_idx` (`phone_number` ASC),
  CONSTRAINT `fk_texts_phone_numbers1`
    FOREIGN KEY (`phone_number`)
    REFERENCES `impulse`.`phone_numbers` (`number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `impulse`.`data_transfer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `impulse`.`data_transfer` ;

CREATE TABLE IF NOT EXISTS `impulse`.`data_transfer` (
  `phone_number` INT NOT NULL,
  `size` INT NOT NULL COMMENT 'In KB',
  `use_time` DATETIME NOT NULL,
  INDEX `fk_data_transfer_phone_numbers1_idx` (`phone_number` ASC),
  CONSTRAINT `fk_data_transfer_phone_numbers1`
    FOREIGN KEY (`phone_number`)
    REFERENCES `impulse`.`phone_numbers` (`number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
